// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebApi.Models;

#nullable disable

namespace MyWebApi.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20250325035359_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyModels.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Essential Programming Language ",
                            InStock = true,
                            Price = 250,
                            PublishDate = new DateTime(2019, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = " Essential Programming Language "
                        },
                        new
                        {
                            Id = 2,
                            Description = " Telling Arts ",
                            InStock = true,
                            Price = 245,
                            PublishDate = new DateTime(2019, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = " Telling Arts "
                        },
                        new
                        {
                            Id = 3,
                            Description = " Marvel ",
                            InStock = true,
                            Price = 150,
                            PublishDate = new DateTime(2019, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = " Marvel "
                        },
                        new
                        {
                            Id = 4,
                            Description = " The Beauty of Cook ",
                            InStock = true,
                            Price = 450,
                            PublishDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = " The Beauty of Cook"
                        },
                        new
                        {
                            Id = 5,
                            Description = " Learning how to Cook  ",
                            InStock = true,
                            Price = 450,
                            PublishDate = new DateTime(2020, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = " Learning how to Cook "
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
